version: '3'
services:
  database:
    image: postgres:11.1
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "p0stgr@s_dev"
      POSTGRES_DB:       "eagle_eye_dev"

  configserver:
      image: alice/confsvr:chapter3
      ports:
        - "8888:8888"
      environment:
        ENCRYPT_KEY:       "IMSYMMETRIC"   

  licensingservice:
     image: alice/licensing-service:chapter2
     ports:
       - "8080:8080"
     environment:
       PROFILE: "dev"
       CONFIGSERVER_URI: "http://configserver:8888"
       CONFIGSERVER_PORT:   "8888"
       DATABASESERVER_PORT: "5432"
