version: '3'
services:
  licensingservice:
      image: alice/licensing-service:chapter2
      ports:
        - "8080:8080"
  configserver:
      image: alice/confsvr:chapter3
      ports:
        - "8888:8888"      