server:
  port: 8888
spring:
 profiles:
   active: native
 cloud:
    config:
      server:
          native:
             searchLocations: file:///Users/santoshkc/springboot/springboot-chapter-2/confsvr/src/main/resources/config/licensingservice
